### ISSUE TITLE
City Bars Example - No controller action after pop

### ISSUE THREAD

**Issue by crema1984** [SenchaArchitect/CityBars#2]
Dear Phil,

I am very new at sencha touch and I tried this example with the Architect 2.1.0 588. It works fine! 
But when i try to add a controller action to the call/more button on the DetailPanel like this

Code:
onButtonTap: function(button, e, options) {
  console.log('botton tap');
},

with following reference

Code:
control: {
   "#dataList": {  
       itemtap: 'onListItemTap' 
   },  
    "#callButton": {
       tap: 'onButtonTap'
   }  
}

it still works till I press the back button off the navigation bar. If I tap on a new listItem afterwards, the buttons on the new created DetailPanel are without function. Is my referencing wrong? But I am referencing ui components in the same way as in the example application.
In my opinion this example is one of the best for beginners but it end to soon and on a very interesting point.

**Comment by philstrong** [comment]
So this won't work in this way because the call button isn't available when the controller sets up.  Instead you would need to add the listener in onListItemTap (when you're creating the detailPanel

https://github.com/SenchaArchitect/CityBars/blob/master/app/controller/Business.js#L34

after you've created you could use component query to add the listener

details.down('button[text="Call"]').on('tap', this.onCallButtonTap);

**Comment by philstrong** [comment]
A clearer way to say it is the detailPanel is created on the fly when you tap a list item.  So you won't be able to use a controller reference

**Comment by philstrong** [comment]
Ok I made a mistake the references are checked at event fire so a controller ref here would work.

I suspect it's because your query is wrong.

I tested it an you can use 

detailpanel button[text='Call']   <-- note the single quotes

**Comment by crema1984** [comment]
Thank you very much! I followed your advice and it works. 
But is that the officially way for referencing? In my opinion a label based query for a button looks like a workaround and may end in avoidable refactoring. I tried following query and it works too:

detailpanel button[id='callButton']

It's very annoying that such fundamental things are not described clearly in the getting started tutorials of sencha touch and sencha architect. For a beginner, it's totally confusing getting the reference of one ui component with selector tags, like
"#dataList": { itemtap: 'onListItemTap' }
and of one another ui component with a xtype based solution, like
detailpanel button[text='Call'] { tap: 'onButtonTap'}. 
Why you don't use the second solution for the dataList in CityBars?

**Comment by philstrong** [comment]
So you're correct we can and will do a better job explaining selectors.  A fair point about future refactors.  I was sort of showing off yet another way but not the best way.  In the end you should decide what works best for your application.  Using the text is poor when you start to think about i18n
